config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :comments
  resources :posts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :attachment
  has_many :comments, dependent: :destroy 
  accepts_nested_attributes_for :attachment
  validates :title, :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :post_params, only: [:create]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.where(id: params[:ids])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.create(post_params)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :likes, :reaction, :tags, :attachment_id, :comment_id, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <button type="submit" class="btn btn-success">Create Post</button>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editing Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>Posts</h2>

<section class="cards">
<% @posts.reverse.each do |post| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.body %></p>

      <section class="card-buttons">
        <% if post.comments.count >= 0 && user_signed_in? %>
          <%= link_to 'Add Comment', new_comment_path(:comment, post_id: post.id), class:"btn btn-light"%>
        <% end %>

        <% if post.comments.count >= 1 %> 
          <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#tag_<%=post.id%>" aria-expanded="false" aria-controls="collapseExample">
            Show Comments
          </button>

          <div class="collapse" id="tag_<%=post.id%>">
            <div class="card card-body">
              <% post.comments.each do |comment| %>
                - <%= comment.body %>  <strong>Written by: <%= comment.user.first_name%></strong>
                <br>
              <% end %>
            </div>
          </div>
        <% end %> 

        <% if user_signed_in? && current_user.id == post.user_id %>
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-light" %>
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>
      </section>
    </div>
  </div>
<% end %>
</section>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @post.likes %>
</p>

<p>
  <strong>Reaction:</strong>
  <%= @post.reaction %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tags %>
</p>

<%# <p>
  <strong>Attachment:</strong>
  <%= @post.attachment_id %>
<%# </p> %> 

<%# <p> %>
  <%# <strong>Comment:</strong> %>
  <%# <%= @post.comment_id %>
<%# </p> %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>